0.9e

diff --git a/PortablePipeline/scripts/annotation~Trinotate b/PortablePipeline/scripts/annotation~Trinotate
--- a/PortablePipeline/scripts/annotation~Trinotate
+++ b/PortablePipeline/scripts/annotation~Trinotate
@@ -4,8 +4,8 @@ explanation='
 add Trinotate annotation
 '
 inputdef='
-input_1::contig file:*.fasta,*.fa,*.fsa,*.fna
-input_2::gene2isoform map file:*
+input_1::Assembled cDNA contigs:*.fasta,*.fa,*.fsa,*.fna
+input_2:option:gene2isoform map file:*
 '
 optiondef='
 opt_c:cpu threads:8
@@ -15,21 +15,28 @@ runcmd="$0 -c #opt_c# -m #opt_m# #input_1# #input_2#"
 
 export IM_TRINOTATE="c2997108/centos7:1-trinity_2.8.5-kallisto_0.46.0-blast_2.9.0-trinotate-3.1.1-R_3-kegg_2"
 export IM_BLASTN="c2997108/centos7:1-blast_2.9.0-nt_20190618-13"
-export IM_MERGE="c2997108/centos6:3"
+export IM_MERGE="c2997108/centos7:3-java"
 
 source $(dirname `readlink -f $0 || echo $0`)/common.sh
 
 set -eux
 set -o pipefail
 
-fasta=$input_1
-gene2trans=$input_2
+fasta="$input_1"
+
+if [ -e "$input_2" ]; then
+ gene2trans="$input_2"
+else
+ grep "^>" "$fasta"|awk '{a=substr($1,2); print a"\t"a}' > input.gene2trans
+ gene2trans=input.gene2trans
+fi
 
 
 DO_TRINOTATE /usr/local/TransDecoder-TransDecoder-v5.5.0/TransDecoder.LongOrfs -t $fasta
-DO_TRINOTATE /usr/local/TransDecoder-TransDecoder-v5.5.0/TransDecoder.Predict -t $fasta --cpu $N_CPU
+DO_TRINOTATE /usr/local/TransDecoder-TransDecoder-v5.5.0/TransDecoder.Predict -t $fasta --cpu $N_CPU || (echo "ERROR: There is no protein sequence in your FASTA file"; exit 1)
 
 transfasta=`basename $fasta`
+DO_TRINOTATE rm -rf $transfasta.transdecoder_dir $transfasta.transdecoder_dir.__checkpoints_longorfs $transfasta.transdecoder_dir.__checkpoints
 
 echo '
  '$ENV_TRINOTATE' blastx -db /usr/local/Trinotate-Trinotate-v3.1.1/db/uniprot_sprot.pep -query '$fasta' -num_threads '$N_CPU' -max_target_seqs 1 -outfmt 6 -evalue 1e-5 > swissprot.blastx.outfmt6
@@ -89,9 +96,13 @@ EOF
 DO_TRINOTATE bash run-kegg.sh
 DO_BLASTN zcat /usr/local/db/nt.2019-06-18/nt.name.gz | DO_TRINOTATE awk -F'\t' 'FILENAME==ARGV[1]{id[$1]=$2; sim[$1]=$3; len[$1]=$4; eval[$1]=$11; flagname[$2]=1} FILENAME==ARGV[2]{if(flagname[$1]==1){name[$1]=$2}else{delete flagname[$1]}} FILENAME==ARGV[3]{if(FNR==1){print $0"\tNCBI NT top hit\te-value\tsimilarity\thit length"}else{if(name[id[$2]]==""){name[id[$2]]=id[$2]}; print $0"\t"name[id[$2]]"\t"eval[$2]"\t"sim[$2]"\t"len[$2]}}' $fasta.blastn /dev/stdin Trinotate.xls2 > Trinotate.xls3
 
-DO_TRINOTATE awk -F'\t' '{ORS=""; print $2"\t"$1; for(i=3;i<=NF;i++){print "\t"$i}; print "\n"}' Trinotate.xls3 > Trinotate.xls3.isoform
+DO_TRINOTATE awk -F'\t' '{ORS=""; print $2"\t"$1; for(i=3;i<=NF;i++){print "\t"$i}; print "\n"}' Trinotate.xls3 |
+ DO_TRINOTATE awk -F'\t' 'NR==1{for(i=2;i<=NF;i++){if($i=="sprot_Top_BLASTP_hit"){n=i}}; OFS="\t"} {if(NR==1){$n="gene_name_from_sprot\t"$n}else{split($n,arr,"_"); $n=arr[1]"\t"$n}; print $0}' > Trinotate.output.txt
 
-
+DO_TRINOTATE rm -rf TMHMM_1
+DO_TRINOTATE rm -f transcriptSuperScaffold.fasta transcriptSuperScaffold.bed tmp.superscaff.rnammer.gff Trinotate.sqlite run-trinotate-import.sh
+DO_TRINOTATE rm -f Trinotate.xls.gene_ontology run-kegg.sh Trinotate.xls2
+DO_TRINOTATE rm -f pipeliner.*.cmds tmp.rnammer_bulk_load.* tmp.signalp_bulk_load.*
 
 post_processing
 
